---

replicaCount: 3

env:
  STAGE_ENVIRONMENT: "HNI-PRODUCTION"
  APP_NAME: "FRONTEND APPLICATION"
  
image:
  repository: thanh-harbor.iij.org.vn/thanh-project/frontend-application
  pullPolicy: IfNotPresent
  tag: 2.0.0

service:
  type: LoadBalancer
  port: 80
