---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thanh-fullend-chart.fullname" . }}
  labels:
    {{- include "thanh-fullend-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.fullend.replicaCount }}
  selector:
    matchLabels:
      {{- include "thanh-fullend-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.fullend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "thanh-fullend-chart.labels" . | nindent 8 }}
        {{- with .Values.fullend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.fullend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.fullend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.fullend.securityContext | nindent 12 }}
          image: "{{ .Values.fullend.image.repository }}:{{ .Values.fullend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.fullend.image.pullPolicy }}
          env:
            - name: STAGE_ENVIRONMENT
              value: "{{ .Values.fullend.env.STAGE_ENVIRONMENT }}"
            - name: APP_NAME
              value: "{{ .Values.fullend.env.APP_NAME }}"
            - name: REDIS_HOST
              value: "{{ include "thanh-fullend-chart.fullname" . }}rsv"
            - name: REDIS_PORT
              value: "6379"
          ports:
            - name: http
              containerPort: {{ .Values.fullend.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.fullend.resources | nindent 12 }}
          {{- with .Values.fullend.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.fullend.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fullend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fullend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fullend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
