---

replicaCount: 2

env:
  STAGE_ENVIRONMENT: "HCM-PRODUCTION"
  APP_NAME: "FRONTEND APPLICATION"
  
image:
  repository: 192.168.145.182/kargo/frontend-app
  pullPolicy: IfNotPresent
  tag: 5.0.0

service:
  type: LoadBalancer
  port: 80
