---

replicaCount: 2

env:
  STAGE_ENVIRONMENT: "DEV-ENVIRONMENT"
  APP_NAME: "FRONTEND APPLICATION"
  
image:
  repository: dvanthanh1992/be-test
  pullPolicy: IfNotPresent
  tag: 1.0.0

service:
  type: LoadBalancer
  port: 80
