---

replicaCount: 2

env:
  STAGE_ENVIRONMENT: "DEV-ENVIRONMENT"
  APP_NAME: "FRONTEND APPLICATION"
  
image:
  repository: 192.168.145.112/kargo/frontend-app
  pullPolicy: IfNotPresent
  tag: 1.0.0

service:
  type: LoadBalancer
  port: 80
