---

replicaCount: 2

env:
  STAGE_ENVIRONMENT: "DEV-ENVIRONMENT"
  APP_NAME: "FRONTEND APPLICATION"
  
image:
  repository: binh-harbor.iij.org.vn/binh-project/frontend-application
  pullPolicy: IfNotPresent
  tag: 3.0.0

service:
  type: LoadBalancer
  port: 80
