---

fullend:
  replicaCount: 2

  env:
    STAGE_ENVIRONMENT: "STG-ENVIRONMENT"
    APP_NAME: "FULLEND APPLICATION"

  image:
    repository: oki-harbor.iij.org.vn/oki-project/fullend-application
    tag: 1.0.0
    pullPolicy: Always

  service:
    type: LoadBalancer
    port: 80

redis:
  replicaCount: 1
  image:
    repository: redis
    tag: "6.2"
    pullPolicy: IfNotPresent
  service:
    port: 6379
  pvc:
    storage: 1Gi
