---

replicaCount: 2

env:
  STAGE_ENVIRONMENT: "HCM-PRODUCTION"
  APP_NAME: "BACKEND APPLICATION"

image:
  repository: 192.168.145.112/kargo/backend-app
  pullPolicy: IfNotPresent
  tag: 4.0.0

service:
  type: LoadBalancer
  port: 80
