---
# Source: thanh-backend-chart/templates/app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanh-backend-chart
  labels:
    helm.sh/chart: thanh-backend-chart-1.0.0
    app.kubernetes.io/name: thanh-backend-chart
    app.kubernetes.io/instance: thanh-backend-chart
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: thanh-backend-chart
      app.kubernetes.io/instance: thanh-backend-chart
  template:
    metadata:
      labels:
        helm.sh/chart: thanh-backend-chart-1.0.0
        app.kubernetes.io/name: thanh-backend-chart
        app.kubernetes.io/instance: thanh-backend-chart
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      securityContext:
        null
      containers:
        - name: thanh-backend-chart
          securityContext:
            null
          image: "demo-harbor.iij.org.vn/demo-project/backend-application:3.0.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: STAGE_ENVIRONMENT
              value: "STG-ENVIRONMENT"
            - name: APP_NAME
              value: "BACKEND APPLICATION"
            - name: REDIS_HOST
              value: "thanh-backend-chart-redis-service"
            - name: REDIS_PORT
              value: "6379"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            null
