---
# Source: thanh-backend-chart/templates/app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: thanh-backend-chart
  labels:
    helm.sh/chart: thanh-backend-chart-1.0.0
    app.kubernetes.io/name: thanh-backend-chart
    app.kubernetes.io/instance: thanh-backend-chart
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: thanh-backend-chart
    app.kubernetes.io/instance: thanh-backend-chart
