---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "thanh-backend-chart.fullname" . }}-redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.pvc.storage }}
