---

fullend:
  replicaCount: 4

  env:
    STAGE_ENVIRONMENT: "HCM-PRODUCTION"
    APP_NAME: "FULLEND APPLICATION"

  image:
    repository: demo-harbor.iij.org.vn/demo-project/fullend-application
    tag: 5.0.0
    pullPolicy: Always

  service:
    type: LoadBalancer
    port: 80

redis:
  replicaCount: 1
  image:
    repository: redis
    tag: "6.2"
    pullPolicy: IfNotPresent
  service:
    port: 6379
  pvc:
    storage: 1Gi
