---

replicaCount: 4

env:
  STAGE_ENVIRONMENT: "HCM-PRODUCTION"
  APP_NAME: "BACKEND APPLICATION"

image:
  repository: thanh-harbor.iij.org.vn/thanh-project/backend-application
  pullPolicy: IfNotPresent
  tag: 2.0.0

service:
  type: LoadBalancer
  port: 80
