---

replicaCount: 2

env:
  STAGE_ENVIRONMENT: "STG-ENVIRONMENT"
  APP_NAME: "BACKEND APPLICATION"

image:
  repository: xuong-harbor.iij.org.vn/xuong-project/backend-application
  pullPolicy: IfNotPresent
  tag: 1.0.0

service:
  type: LoadBalancer
  port: 80
