---

replicaCount: 2

env:
  STAGE_ENVIRONMENT: "STG-ENVIRONMENT"
  APP_NAME: "BACKEND APPLICATION"

image:
  repository: ha-harbor.iij.org.vn/ha-project/backend-application
  pullPolicy: IfNotPresent
  tag: 2.0.0

service:
  type: LoadBalancer
  port: 80
