---

replicaCount: 4

env:
  STAGE_ENVIRONMENT: "HCM-PRODUCTION"
  APP_NAME: "FRONTEND APPLICATION"
  
image:
  repository: ha-harbor.iij.org.vn/ha-project/frontend-application
  pullPolicy: IfNotPresent
  tag: 3.0.0

service:
  type: LoadBalancer
  port: 80
