---

replicaCount: 2

env:
  STAGE_ENVIRONMENT: "DEV-ENVIRONMENT"
  APP_NAME: "BACKEND APPLICATION"

image:
  repository: binh-harbor.iij.org.vn/binh-project/backend-application
  pullPolicy: IfNotPresent
  tag: 2.0.0

service:
  type: LoadBalancer
  port: 80
