---

replicaCount: 2

env:
  STAGE_ENVIRONMENT: "DEV-ENVIRONMENT"
  APP_NAME: "BACKEND APPLICATION"

image:
  repository: thanh-harbor.iij.org.vn/thanh-project/backend-application
  pullPolicy: IfNotPresent
  tag: 3.0.0

service:
  type: LoadBalancer
  port: 80
