---
# Source: be-chart/templates/redis.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    helm.sh/chart: be-chart-1.0.0
    app.kubernetes.io/name: be-chart
    app.kubernetes.io/instance: thanh-backend-chart
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app.kubernetes.io/name: be-chart
    app.kubernetes.io/instance: thanh-backend-chart
    app.kubernetes.io/component: redis
---
# Source: be-chart/templates/redis.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanh-backend-chart-be-chart-redis
  labels:
    helm.sh/chart: be-chart-1.0.0
    app.kubernetes.io/name: be-chart
    app.kubernetes.io/instance: thanh-backend-chart
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: be-chart
      app.kubernetes.io/instance: thanh-backend-chart
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: be-chart
        app.kubernetes.io/instance: thanh-backend-chart
        app.kubernetes.io/component: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
