name: Update Index

on:
  push:
    branches: [ main ]
    paths:
      - '**.tgz'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Gituhb Checkout
        uses: actions/checkout@v4
        
      - name: Helm Installation
        uses: azure/setup-helm@v4.2.0
        with:
          version: "latest"

      - name: Update Index
        run: |
            helm repo index .
            git config --global user.email "${GITHUB_ACTOR}@gmail.com"
            git config --global user.name "${GITHUB_ACTOR}"
            git add index.yaml
            git commit -m "Update chart index"
            git push
