---

replicaCount: 4

env:
  STAGE_ENVIRONMENT: "HCM-PRODUCTION"
  APP_NAME: "FRONTEND APPLICATION"
  
image:
  repository: xuong-harbor.iij.org.vn/xuong-project/frontend-application
  pullPolicy: IfNotPresent
  tag: 1.0.0

service:
  type: LoadBalancer
  port: 80
